#!/bin/sh
#
# Update u-boot image on boot device
#
# The boot order (hardcoded in A64) is:
# MMC0 -> MMC2 -> SPI -> FEL
# 
# First with valid eGON header wins
#
#  update-uboot <mmc0|mmc2|spi>
#
# Default if none provided follows above order, first device present is updated
#
BDEV=$1
#BIN=/usr/share/u-boot-pinea64-2/u-boot-pinea64.spl
#u-boot-pinea64-2.spl is built from u-boot v2021.01-rc1-149-g7a8ac9df
BIN=/usr/share/u-boot-pinea64-2/u-boot-pinea64-2.spl
SETENV=/usr/share/u-boot-pinea64-2/fw_setenv

copy_to_dev() {
  s=$1
  dev=""
  seek=0
  bs=8k
  fle=""
  flp=0
  case $s in
    mmc0)
      dev=/dev/mmcblk0
      seek=1
      ;;
    mmc2)
      dev=/dev/mmcblk1
      seek=1
      ;;
    spi)
      # this is normal read-only and will fail
      dev=/dev/mtd1
      fle=flash_erase
      ;;
    spi_FACTORY_danger)
      dev=/dev/mtd0
      # erase 0x00000 to 0xddfff
      fle=flash_erase
      flp=222
      ;;
    *)
      echo "Invalid device $dev"
      exit 2
      ;;
  esac
  if [ ! -w $dev ]; then
    return 1
  fi 

  if [ $BIN = "/usr/share/u-boot-pinea64-2/u-boot-pinea64-2.spl" ]; then
        echo "Using source built bootloader..."
  else
        echo "Using pre-built bootloader..."
  fi 
  
  if [ "$fle" != "" ]; then
    echo "Erasing flash $dev..."
    if ! flash_erase $dev 0 $flp > /dev/null; then
      return 2
    fi
  fi
  echo "Copying to $dev..."
  if ! dd if=$BIN of=$dev bs=$bs seek=$seek 2> /dev/null; then
    return 3
  fi
  sync
  echo "Copied u-boot to $dev"
  # Re ticket #2014 - make sure boot order is correct
  $SETENV boot_targets "next fel pxe usb0 mmc1 mmc0"
  return 0
}

devfs=$(findmnt -n -o FSTYPE /dev 2> /dev/null || true)

if [ "$devfs" != "devtmpfs" ]; then
  # We are not looking at a real /dev, exit cleanly
  echo "Not updating u-boot binary, no dev filesystem present"
  exit 0
fi

if [ "$BDEV" != "" ]; then
	if ! copy_to_dev $BDEV; then 
	  echo "Unable to write to device"
	  exit 1
	fi
else
  for s in mmc0 mmc2 spi; do
    if copy_to_dev $s; then
    	exit 0
    fi
  done
  echo "No writable device found"
  exit 1
fi
